name: Apply Branch Protection Rules

on:
  push:
    branches:
      - main # Change to your branch

jobs:
  apply-branch-protection:
    runs-on: ubuntu-latest

    steps:
      - name: Apply branch protection rules
        run: |
          echo "Applying branch protection rules to ${{ github.repository }}"
          echo "token: ${{ secrets.TOK }}"

          curl -X PUT \
            -H "Authorization: token ${{ secrets.TOK }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{
              "required_status_checks": {
                "strict": true,
                "contexts": ["ci/travis"]
              },
              "enforce_admins": true,
              "required_pull_request_reviews": {
                "dismissal_restrictions": {
                  "users": ["ahmedamsoliman-1"],
                  "teams": []
                },
                "dismiss_stale_reviews": true,
                "require_code_owner_reviews": true,
                "required_approving_review_count": 1
              },
              "restrictions": {
                "users": ["user1"],
                "teams": []
              },
              "required_linear_history": true,
              "allow_force_pushes": false,
              "allow_deletions": false
            }' \
            https://api.github.com/repos/${{ github.repository }}/branches/main/protection
        env:
          MY_GITHUB_PAT: ${{ secrets.TOK }}
