name: Apply Branch Protection

on:
  push:
    branches:
      - main # Change to your branch name

jobs:
  branch-protection:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Apply branch protection rules
        uses: peter-evans/branch-protection@v3
        with:
          branch: main # Change to your branch name
          required_status_checks: 'ci/circleci: build'
          required_approving_review_count: 2
          dismiss_stale_reviews: true
          require_code_owner_reviews: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
