name: Apply Repository Rules

on:
  push:
    branches:
      - main # Change to your branch

jobs:
  apply-repository-rules:
    runs-on: ubuntu-latest

    steps:
      - name: Apply repository rules
        run: |
          echo "Applying repository rules to ${{ github.repository }}"

          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{
              "name": "Manuall Protection",
              "target": "branch",
              "source_type": "Repository",
              "source": "${{ github.repository }}",
              "enforcement": "active",
              "conditions": {
                "ref_name": {
                  "exclude": [],
                  "include": [
                    "~DEFAULT_BRANCH"
                  ]
                }
              },
              "rules": [
                {
                  "type": "deletion"
                },
                {
                  "type": "non_fast_forward"
                },
                {
                  "type": "creation"
                }
              ],
              "bypass_actors": []
            }' \
            https://api.github.com/repos/${{ github.repository }}/branch_protection/rules
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
